chore: update specmatic-kafka version to 1.2.0 & add ctrf report generation

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -26,6 +26,29 @@ jobs:
     - name: Build BFF project with Gradle
       run: ./gradlew build
 
+    # Set up Node.js for CTRF conversion
+    - name: Setup Node.js
+      uses: actions/setup-node@v4
+      with:
+        node-version: '18'
+
+    - name: List build directory
+      run: ls -R build || true
+    
+    # Convert JUnit XML to CTRF format
+    - name: Convert JUnit to CTRF
+      if: always() # Run even if tests fail
+      run: |
+        npx junit-to-ctrf build/test-results/test/TEST-com.component.orders.contract.ContractTests.xml --output ctrf/ctrf-report.json
+    
+    # Display CTRF test results
+    - name: Publish Test Results
+      uses: ctrf-io/github-test-reporter@v1
+      if: always() # Run even if tests fail
+      with:
+        report-path: './ctrf/*.json'
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+
     - name: Run coverage report
       run: ./gradlew jacocoTestReport
 
